### ISSUE TITLE
Prototype a library for converting between human genomes

### ISSUE THREAD

**Issue by mcupak** [mcupak/genome-coordinates-converter#1]
We need a Java component capable of converting coordinates between assemblies. There are hosted services as well as command line tools capable of doing this, we need one that we can use from Java. This will be an important component used by beacons as well as the Beacon Network.

See e.g. https://www.biostars.org/p/65558/ for information about the current tools. Feel free to search for others.

Requirements:
- Supports standard human assemblies (at least hg18, hg19, hg38). Let's not focus on other species yet.
- Does not implement an algorithm from scratch. Wraps one of the available tools instead.
- Doing the conversion locally is strongly preferred over contacting a remote API to do the conversion due to latency. Most likely, this will involve calling a library written in another language from Java code.
- Thread safety. The component will be used in a client-server environment satisfying many concurrent requests. This cannot cause any resource contention. Pay attention to this especially when wrapping a non-Java tool.
- Multi-module Maven project with 2 modules - API (interfaces providing API methods) and IMPL (the actual library implementation). API module should not have any non-trivial dependencies on external libraries. The application using the library should include the API module as a compile-time and IMPL module as a runtime dependency.
- Ideally, the library should package all its dependencies through Maven. When using an external non-Java tool, see if you can bundle and run it somehow without expecting the operator to have the tool installed on the server outside of the project build.
- License allowing for commercial as well as non-commercial use. Some of the available tools can be used for non-commercial purposes only. Make sure you choose a tool that can be used freely in commercial setting as well. Let's use this issue to discuss the options.

**Comment by mfiume** [comment]
Should it be pure Java?

Maybe we can wrap https://pypi.python.org/pypi/pyliftover.

**Comment by mfiume** [comment]
This may do the trick:

https://samtools.github.io/htsjdk/javadoc/htsjdk/htsjdk/samtools/liftover/LiftOver.html

**Comment by mcupak** [comment]
Another relevant link: https://bitbucket.org/biocommons/hgvs

**Comment by mcupak** [comment]
Finally got a chance to review this in some more depth. Since this was pushed rather than submitted via a pull request, let's track the feedback here. This issue can be resolved once these comments are addressed. More complicated things will be filed separately.
- The code does not compile due to improperly set up dependencies. Example:

```
$ mvn clean install
[INFO] Scanning for projects...
[INFO]
[INFO] ------------------------------------------------------------------------
[INFO] Building genome-coordinates-converter 1.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 0.530 s
[INFO] Finished at: 2016-06-10T16:05:37-04:00
[INFO] Final Memory: 8M/245M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal on project genome-coordinates-converter: Could not resolve dependencies for project groupId:genome-coordinates-converter:jar:1.0-SNAPSHOT: Failed to collect dependencies at junit:junit:jar:RELEASE -> org.hamcrest:hamcrest-core:jar:1.3-redhat-1: Failed to read artifact descriptor for org.hamcrest:hamcrest-core:jar:1.3-redhat-1: Failure to find org.hamcrest:hamcrest-parent:pom:1.3-redhat-1 in https://dev.dnastack.com/nexus/content/repositories/releases was cached in the local repository, resolution will not be reattempted until the update interval of dnastack-releases has elapsed or updates are forced -> [Help 1]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/DependencyResolutionException
```
- It should be clear what is API and what is not meant to be used by the user of the library. The should be an API package with the appropriate interfaces, which the implementation should implement. Only the methods meant to be used by the user of the library should be public, other methods should be private or package-private, depending on what scope is needed. Consider splitting the API to a separate modules, as suggested in the description of the issue.
- Package names should be lowercase rather than CamelCase (convention).
- Why is @SuppressWarnings("WeakerAccess") needed on LiftOverException?
- The files should have Apache 2-compatible license header.

@patmagee Can you please take a look at these?
